name: CI

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize]
    push:
        branches: [main]

jobs:
    avoid_redundancy_lint_pretty_and_cache_deps:
        runs-on: ubuntu-22.04
        permissions: write-all
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}
                  
            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v4
              with:
                  cache: 'pnpm'
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  same_commit: true
                  prettier_options: . --write

    translate:
        needs: [avoid_redundancy_lint_pretty_and_cache_deps]
        runs-on: ubuntu-22.04
        permissions:
          contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v4
              with:
                  cache: 'pnpm'
                  node-version: 20

            - name: Install dependencies
              run: pnpm install
              
            - name: Translate
              run: pnpm run start

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Sync translations
                commit_user_name: Discord